name: Build lib
on:
  push:
    paths:
      - .github/workflows/build_lib.yml

env:
  RUBBERBAND_REPO: breakfastquay/rubberband
  RUBBERBAND_VERSION: 'v4.0.0'

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ env.RUBBERBAND_REPO }}
        ref: ${{ env.RUBBERBAND_VERSION }}
    - uses: microsoft/setup-msbuild@v2
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: pip install meson ninja
    - run: |
        meson setup build
        ninja -C build
    - run: tar -czvf rubberband_${{ env.RUBBERBAND_VERSION }}_windows.tar.gz rubberband build
    - uses: actions/upload-artifact@v4
      with:
        name: rubberband_${{ env.RUBBERBAND_VERSION }}_windows
        path: rubberband_${{ env.RUBBERBAND_VERSION }}_windows.tar.gz
