name: Build
on: push

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install
      run: pip install . -v

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install
      run: pip install . -v

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    # - uses: microsoft/setup-msbuild@v2
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install
      run: pip install . -v
